# Generated by Django 3.1.7 on 2021-05-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('img', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
